include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
linter:
  rules:
    public_member_api_docs: false
    depend_on_referenced_packages: false
    sort_pub_dependencies: false