name: authentication_repository
description: authentication_repository
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.5.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  network_client:
    path: ../network_client
  very_good_analysis: ^7.0.0
  json_serializable: ^6.9.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
